### PR TITLE
Added roundClock widget

### PR DESCRIPTION
**Pull request by phaseOne**
Note that I added the screenshot as a retina JPG to save space [with the same amount of quality as a PNG when scaled](http://silev.org/test/Retina-resize.html).

### CODE REVIEW

**Comment by joecreighton** [comment]
Based on the issue https://github.com/phaseOne/roundClock/issues/3 , I made a pull-request but the owner has been away for about ten months.

https://github.com/joecreighton/roundClock

**Comment by felixhageloh** [comment]
@joecreighton in case @phaseOne remains unresponsive, would you want to take over this widget?

**Comment by joecreighton** [comment]
Sure.  I'll only take second billing in the credits, though:  I don't expect much feature creep after this patch :)

**Comment by felixhageloh** [comment]
I like the humbleness @joecreighton! @phaseOne please let us know by the end of the week if you have any objections. If not, @joecreighton you can create a fork of the widget and I will substitute the repo in the widget gallery with the new fork

**Comment by phaseOne** [comment]
@felixhageloh @joecreighton Will roll it in. The life of a working university student means that I'm slow to changes outside of my current focus. Sorry it took so long.

**Comment by felixhageloh** [comment]
great, sounds like this got resolved :)

**Comment by joecreighton** [comment]
@phaseOne Feel free to remove my name and treat it like any other pull-request.

**Comment by phaseOne** [comment]
@felixhageloh @joecreighton PR rolled in today.

**Comment by felixhageloh** [comment]
any action needed from my end still :)?

**Comment by phaseOne** [comment]
@felixhageloh All good now. Thanks!

**Pull request merged**
